// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9cI1sGzKdo-oMWamGnR3qROSKuCdDyfA',
    appId: '1:786964073400:web:91db3e0cc16b49f16fdd4d',
    messagingSenderId: '786964073400',
    projectId: 'bookdoc-205c5',
    authDomain: 'bookdoc-205c5.firebaseapp.com',
    storageBucket: 'bookdoc-205c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKPOapZZL0zssFHGZYK32g6zbnVjuaNxE',
    appId: '1:786964073400:android:42ad07be7c85891e6fdd4d',
    messagingSenderId: '786964073400',
    projectId: 'bookdoc-205c5',
    storageBucket: 'bookdoc-205c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsLh-nCYKv8GdzBXf2I5JelOg8xttrvVo',
    appId: '1:786964073400:ios:0da4b420b363bb496fdd4d',
    messagingSenderId: '786964073400',
    projectId: 'bookdoc-205c5',
    storageBucket: 'bookdoc-205c5.appspot.com',
    iosClientId: '786964073400-bdjotq723p9pas0c5mdql0mj6riss9nr.apps.googleusercontent.com',
    iosBundleId: 'com.appetizers.bookdoc',
  );
}
